import { expect, test } from '@playwright/test';
import path from 'node:path';

const fixturePath = path.resolve('tests/fixtures/minimal_plan.xml');

test.describe('AI features UI and Flow', () => {

  test('displays unconfigured message when AI is not configured', async ({ page }) => {
    // Intercept config endpoint to return disabled/unconfigured state
    await page.route('/api/ai/config', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          enabled: false,
          model: '',
          endpoint: '',
          message: 'AI features are unconfigured or disabled on this workstation.'
        })
      });
    });

    await page.goto('/');

    // Check AI Docs tab message
    await page.locator('#ai-docs-tab').click();
    await expect(page.locator('#ai-docs-unconfigured')).toBeVisible();
    await expect(page.locator('#ai-docs-unconfigured')).toContainText('AI features are unconfigured');
    await expect(page.locator('#generate-ai-docs-button')).not.toBeVisible();

    // Check Details pane AI Summary message (by default with no node selected)
    await page.locator('.tab[data-view="graph-view"]').click();
    await expect(page.locator('#ai-summary-content')).toContainText('Select a node to generate an AI summary');
    await expect(page.locator('#generate-ai-summary-button')).not.toBeVisible();
    await expect(page.locator('#ai-summary-unconfigured')).not.toBeVisible();

    // Generate graph and select a node to trigger selection change
    await page.locator('#np-xml-files').setInputFiles(fixturePath);
    await page.locator('#graph-button').click();
    await expect(page.locator('#status')).not.toHaveText('Generating graph...');

    // Select the first node using cytoscape window object
    await page.evaluate(() => {
      const cy = (window as any).state.cy;
      const node = cy.nodes().first();
      node.select();
      node.emit('tap', { target: node });
    });

    // Check that unconfigured helper message is displayed
    await expect(page.locator('#ai-summary-unconfigured')).toBeVisible();
    await expect(page.locator('#ai-summary-unconfigured')).toContainText('AI features are unconfigured');
    await expect(page.locator('#generate-ai-summary-button')).not.toBeVisible();
  });

  test('successfully triggers summary and documentation when AI is enabled', async ({ page }) => {
    // Intercept config and generation endpoints for success
    await page.route('/api/ai/config', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          enabled: true,
          model: 'mock',
          endpoint: 'http://localhost:11434/v1',
          message: ''
        })
      });
    });

    await page.route('/api/ai/summary', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          text: '### AI Summary: TestNode (Rule)\n\n**Overview:**\nThis is a mock summary of My Node.',
          model: 'mock',
          provider: 'Local Mock Provider',
          timestamp: '2026-07-15T12:00:00.000Z',
          source_identifiers: ['node-1'],
          disclaimer: 'This documentation was generated by AI and requires human review.'
        })
      });
    });

    await page.route('/api/ai/documentation', async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          text: '# SAP Incentive Management Configuration Documentation\n\n## 1. Executive Summary',
          model: 'mock',
          provider: 'Local Mock Provider',
          timestamp: '2026-07-15T12:00:00.000Z',
          source_identifiers: ['snapshot-1'],
          disclaimer: 'This documentation was generated by AI and requires human review.'
        })
      });
    });

    await page.goto('/');

    // 1. Generate graph first to enable generate docs button
    await page.locator('#np-xml-files').setInputFiles(fixturePath);
    await page.locator('#graph-button').click();
    await expect(page.locator('#status')).not.toHaveText('Generating graph...');

    // Select a node
    await page.evaluate(() => {
      const cy = (window as any).state.cy;
      const node = cy.nodes().first();
      node.select();
      node.emit('tap', { target: node });
    });

    // Check summary panel is ready and click generate
    await expect(page.locator('#generate-ai-summary-button')).toBeVisible();
    await page.locator('#generate-ai-summary-button').click();

    // Verify generated summary content & metadata
    await expect(page.locator('#ai-summary-content .ai-disclaimer')).toContainText('human review');
    await expect(page.locator('#ai-summary-content h3')).toContainText('AI Summary: TestNode (Rule)');
    await expect(page.locator('#ai-summary-content .ai-metadata-footer')).toContainText('Local Mock Provider');

    // 2. Go to AI Docs tab and generate full system documentation
    await page.locator('#ai-docs-tab').click();
    await expect(page.locator('#generate-ai-docs-button')).toBeVisible();
    await expect(page.locator('#generate-ai-docs-button')).toBeEnabled();

    await page.locator('#generate-ai-docs-button').click();

    // Verify generated documentation content, download link & metadata
    await expect(page.locator('#ai-docs-text h1')).toContainText('SAP Incentive Management Configuration Documentation');
    await expect(page.locator('#ai-docs-metadata')).toContainText('Local Mock Provider');
    await expect(page.locator('#download-ai-docs')).toBeVisible();
  });
});
