from __future__ import annotations

import os
import json
from abc import ABC, abstractmethod
from datetime import datetime, timezone
from urllib.parse import urlparse
import httpx

class AIError(Exception):
    """Exception raised for errors during AI generation."""
    pass

class AIProvider(ABC):
    @abstractmethod
    def generate_documentation(self, filename: str, content: bytes, nodes_info: list[dict]) -> dict:
        """
        Generate a readable documentation draft from an XML export.
        """
        pass

class StubAIProvider(AIProvider):
    def __init__(self, model: str = "stub-model-v1") -> None:
        self.model = model

    def generate_documentation(self, filename: str, content: bytes, nodes_info: list[dict]) -> dict:
        timestamp = datetime.now(timezone.utc).isoformat()
        source_objects = [f"{node.get('type')}: {node.get('label')}" for node in nodes_info]

        draft_lines = [
            f"# AI-Generated Configuration Draft: {filename}",
            f"**Generated by:** Local Stub Provider ({self.model})",
            f"**Timestamp:** {timestamp}",
            "",
            "## Disclaimer",
            "CRITICAL: This is an automatically generated draft and requires human review. Do not rely solely on this text for production deployments.",
            "",
            "## Overview",
            f"This draft documents the SAP Incentive Management configuration uploaded as `{filename}`.",
            "It contains extracted configuration definitions and identifies source reference evidence.",
            "",
            "## Source Configuration Objects",
            "The following authentic objects were identified in the source XML file. No external or inferred nodes have been invented.",
            ""
        ]

        if not source_objects:
            draft_lines.append("- No configuration objects identified in this export.")
        else:
            for obj in sorted(source_objects):
                draft_lines.append(f"- **{obj}**")

        draft_lines.extend([
            "",
            "## Bounded Reference Evidence",
            "All documented elements strictly correspond to extracted elements without inventing graph nodes or hallucinating relations.",
        ])

        draft = "\n".join(draft_lines)
        return {
            "draft": draft,
            "provider": "stub",
            "model": self.model,
            "timestamp": timestamp,
            "source_objects": [node.get("canonicalKey") or node.get("id") for node in nodes_info if node.get("id")],
            "disclaimer": "This is an AI-generated draft and requires human review. It does not invent graph nodes."
        }

class OpenAIProvider(AIProvider):
    def __init__(self, endpoint: str, model: str = "gpt-3.5-turbo") -> None:
        self.endpoint = endpoint
        self.model = model
        self._validate_endpoint(endpoint)

    def _validate_endpoint(self, endpoint: str) -> None:
        parsed = urlparse(endpoint)
        host = parsed.hostname
        if not host:
            raise AIError("Invalid AI endpoint URL configured.")

        is_loopback = host in {"localhost", "127.0.0.1", "[::1]", "::1"}
        if not is_loopback:
            raise AIError(f"Remote AI endpoints are rejected by default: '{host}' is not a local loopback address.")

    def generate_documentation(self, filename: str, content: bytes, nodes_info: list[dict]) -> dict:
        timestamp = datetime.now(timezone.utc).isoformat()
        serialized_nodes = []
        for n in nodes_info:
            serialized_nodes.append({
                "id": n.get("id"),
                "label": n.get("label"),
                "type": n.get("type"),
                "canonicalKey": n.get("canonicalKey"),
                "xmlPath": n.get("xmlPath")
            })

        system_prompt = (
            "You are a technical writer specialized in SAP Incentive Management configurations.\n"
            "Your task is to generate structured, readable documentation from a list of configuration nodes extracted from an XML export.\n"
            "PRODUCT INVARIANT: You must strictly identify relevant source objects and preserve source references.\n"
            "CRITICAL WARNING: Do NOT invent or infer any graph nodes, objects, or relationships not explicitly provided in the source. Do not hypothesize about configuration elements that are missing from the list.\n"
            "Clearly label the text as an AI-generated draft requiring human review."
        )

        user_prompt = (
            f"Please generate a structured documentation draft for the configuration file '{filename}'.\n"
            f"Here are the authentic configuration nodes extracted from the file:\n"
            f"{json.dumps(serialized_nodes, indent=2)}\n"
        )

        headers = {
            "Content-Type": "application/json"
        }
        api_key = os.environ.get("SAP_IM_AI_API_KEY")
        if api_key:
            headers["Authorization"] = f"Bearer {api_key}"

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            "temperature": 0.2
        }

        try:
            with httpx.Client(timeout=30.0) as client:
                response = client.post(self.endpoint, json=payload, headers=headers)

            if response.status_code != 200:
                raise AIError(f"AI Provider returned error status {response.status_code}: {response.text}")

            resp_data = response.json()
            choices = resp_data.get("choices")
            if not choices or not isinstance(choices, list) or len(choices) == 0:
                raise AIError("AI Provider returned an empty response choices list.")

            draft_text = choices[0].get("message", {}).get("content", "")
            if not draft_text:
                raise AIError("AI Provider returned empty message content.")

            return {
                "draft": draft_text,
                "provider": "openai",
                "model": self.model,
                "timestamp": timestamp,
                "source_objects": [node.get("canonicalKey") or node.get("id") for node in nodes_info if node.get("id")],
                "disclaimer": "This is an AI-generated draft and requires human review. It does not invent graph nodes."
            }
        except httpx.RequestError as exc:
            raise AIError(f"HTTP request to AI endpoint failed: {exc}") from exc
        except Exception as exc:
            if not isinstance(exc, AIError):
                raise AIError(f"Unexpected error during AI generation: {exc}") from exc
            raise

def get_ai_provider() -> AIProvider | None:
    provider_type = os.environ.get("SAP_IM_AI_PROVIDER", "").strip().lower()
    if not provider_type:
        return None

    model = os.environ.get("SAP_IM_AI_MODEL", "gpt-3.5-turbo").strip()

    if provider_type == "stub":
        return StubAIProvider(model=model)
    elif provider_type == "openai":
        endpoint = os.environ.get("SAP_IM_AI_ENDPOINT", "").strip()
        if not endpoint:
            raise AIError("SAP_IM_AI_ENDPOINT is required when provider is 'openai'.")
        return OpenAIProvider(endpoint=endpoint, model=model)
    else:
        raise AIError(f"Unsupported AI provider type: {provider_type}")
