import os
import socket
from datetime import datetime, timezone
from typing import Any, Optional
from urllib.parse import urlparse

import httpx


class AIProviderError(Exception):
    pass


def is_ai_configured() -> bool:
    return check_ai_configuration()[0]


def check_ai_configuration() -> tuple[bool, str]:
    if "SAP_IM_AI_ENDPOINT" in os.environ or "SAP_IM_AI_MODEL" in os.environ:
        endpoint = os.environ.get("SAP_IM_AI_ENDPOINT")
        model = os.environ.get("SAP_IM_AI_MODEL")
        if not endpoint or not model:
            return False, "AI features are unconfigured or disabled on this workstation."

        # If model is 'mock', allow any loopback-like or mock endpoint for testing
        if model == "mock":
            return True, ""

        try:
            parsed = urlparse(endpoint)
            hostname = parsed.hostname
            if not hostname:
                return False, "Invalid AI endpoint URL configured."
            if hostname in ("localhost", "127.0.0.1", "::1"):
                return True, ""
            # Resolve hostname
            ips = socket.getaddrinfo(hostname, None)
            for ip in ips:
                addr = ip[4][0]
                if addr in ("127.0.0.1", "::1") or addr.startswith("127."):
                    continue
                else:
                    return False, f"Remote AI endpoints are rejected by default: {endpoint} (only loopback is supported)."
            return True, ""
        except Exception as exc:
            return False, f"Failed to validate AI endpoint: {exc}"

    ai_provider = os.getenv("AI_PROVIDER", "").lower()
    if ai_provider == "openai":
        has_key = bool(os.getenv("OPENAI_API_KEY"))
        return has_key, "OpenAI provider is active." if has_key else "OpenAI provider requires OPENAI_API_KEY."
    elif ai_provider == "gemini":
        has_key = bool(os.getenv("GEMINI_API_KEY"))
        return has_key, "Gemini provider is active." if has_key else "Gemini provider requires GEMINI_API_KEY."
    elif ai_provider == "ollama":
        return True, "Ollama provider is active."
    elif ai_provider == "stub":
        return True, "Stub provider is active."

    return False, "AI features are unconfigured or disabled on this workstation."


def generate_summary(node_data: dict[str, Any]) -> dict[str, Any]:
    ok, err_msg = check_ai_configuration()
    if not ok:
        raise AIProviderError(err_msg)

    node_id = node_data.get("id") or node_data.get("nodeId", "unknown")
    node_name = node_data.get("label", "unknown")
    node_type = node_data.get("type", "unknown")
    source_file = node_data.get("sourceFile", "unknown")
    xml_path = node_data.get("xmlPath", "unknown")
    raw_xml = node_data.get("rawXml", "")
    metadata = node_data.get("metadata", {})

    model = os.environ.get("SAP_IM_AI_MODEL", "mock")
    endpoint = os.environ.get("SAP_IM_AI_ENDPOINT", "http://localhost:11434/v1")
    api_key = os.environ.get("SAP_IM_AI_API_KEY", "")

    timestamp = datetime.now(timezone.utc).isoformat()

    if model == "mock":
        metadata_str = "\n".join(f"- **{k}**: {v}" for k, v in metadata.items()) if metadata else "*None*"
        text = f"""### AI Summary: {node_name} ({node_type})

**Overview:**
This is a mock summary of the configuration object **{node_name}** of type **{node_type}**.
Located in source file `{source_file}` at XML path `{xml_path}`.

**Metadata Properties:**
{metadata_str}

**Relationships & Analysis:**
A mock local-first AI assistant has summarized this object for demonstration purposes. It highlights relationships and attributes found in the original source XML.
"""
        return {
            "text": text,
            "summary": text,
            "model": "mock",
            "provider": "Local Mock Provider",
            "timestamp": timestamp,
            "source_identifiers": [node_id],
            "disclaimer": "This documentation was generated by AI and requires human review.",
        }

    # Otherwise, real loopback OpenAI-compatible endpoint
    system_prompt = "You are a local SAP Incentive Management configuration expert. Analyze the provided object and generate a summary."
    user_prompt = f"""Analyze this configuration object:
Name: {node_name}
Type: {node_type}
Source File: {source_file}
XML Path: {xml_path}
Metadata: {metadata}
XML Source:
{raw_xml}

Generate a clear, structured summary in Markdown describing what this object is, its purpose, its relationships, and any key metadata properties. Ground your response strictly in the provided data. Do not use external knowledge or hallucinate. Maintain privacy; do not make external lookups."""

    payload = {
        "model": model,
        "messages": [
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        "temperature": 0.2,
    }

    headers = {}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    try:
        url = endpoint.rstrip("/") + "/chat/completions"
        with httpx.Client(timeout=10.0) as client:
            resp = client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            data = resp.json()
            text = data["choices"][0]["message"]["content"]
            return {
                "text": text,
                "summary": text,
                "model": model,
                "provider": "Local OpenAI-Compatible",
                "timestamp": timestamp,
                "source_identifiers": [node_id],
                "disclaimer": "This documentation was generated by AI and requires human review.",
            }
    except Exception as exc:
        raise AIProviderError(f"Failed to communicate with AI endpoint: {exc}")


def generate_documentation(graph_doc: dict[str, Any]) -> dict[str, Any]:
    ok, err_msg = check_ai_configuration()
    if not ok:
        raise AIProviderError(err_msg)

    timestamp = datetime.now(timezone.utc).isoformat()
    snapshots = graph_doc.get("snapshots", [])
    nodes = graph_doc.get("nodes", [])
    links = graph_doc.get("links", [])
    findings = graph_doc.get("findings", [])
    topology_mode = graph_doc.get("topologyMode", "core")

    snapshots_str = ", ".join(f"{s.get('id')} ({s.get('role')})" for s in snapshots)
    nodes_count = len(nodes)
    links_count = len(links)
    findings_count = len(findings)

    by_type: dict[str, list[str]] = {}
    for node in nodes:
        nt = node.get("type", "Unknown")
        by_type.setdefault(nt, []).append(node.get("label", "unnamed"))

    nodes_overview_lines = []
    for nt, names in sorted(by_type.items()):
        truncated_names = names[:10]
        suffix = f", ... and {len(names) - 10} more" if len(names) > 10 else ""
        nodes_overview_lines.append(f"- **{nt}** ({len(names)}): {', '.join(truncated_names)}{suffix}")
    nodes_overview = "\n".join(nodes_overview_lines)

    findings_summary = f"{len(findings)} findings present."
    if findings:
        errs = len([f for f in findings if f.get("severity") == "error"])
        warns = len([f for f in findings if f.get("severity") == "warning"])
        findings_summary = f"{errs} errors, {warns} warnings."

    source_ids = [s.get("id") for s in snapshots if s.get("id")]
    ai_provider = os.getenv("AI_PROVIDER", "").lower()
    model = os.environ.get("SAP_IM_AI_MODEL", "")

    if model == "mock" or ai_provider == "stub" or (not model and not ai_provider):
        text = f"""# SAP Incentive Management Configuration Documentation (MOCK)

This documentation was generated from the active XML configuration graph.

## 1. Executive Summary & Provenance
- Snapshots: {snapshots_str or "*None*"}
- Total Nodes: {nodes_count}
- Total Links: {links_count}
- Total Findings: {findings_count}

## 2. Graph Topology & Key Objects
- Topology Mode: {topology_mode}
- Key plans and rule families are present in the source files.

Nodes Grouped By Type:
{nodes_overview or "*None*"}

## 3. Relationship Structure
- Outbound dependency and containment links map structural lineage.

## 4. Validation Findings
- Findings count: {findings_count}
- Summary: {findings_summary}
"""
        return {
            "text": text,
            "model": "mock",
            "provider": "Local Mock Provider",
            "timestamp": timestamp,
            "source_identifiers": source_ids,
            "disclaimer": "This documentation was generated by AI and requires human review.",
        }

    system_prompt = "You are a local SAP Incentive Management configuration expert. Analyze the provided configuration graph summary and generate documentation."
    user_prompt = f"""Generate a comprehensive, high-level system documentation in Markdown based on this configuration summary:
Topology Mode: {topology_mode}
Snapshots: {snapshots_str}
Total Nodes: {nodes_count}
Total Links: {links_count}
Total Findings: {findings_count}

Nodes overview (grouped by type):
{nodes_overview}

Findings summary:
{findings_summary}

Include sections for:
1. Executive Summary and Snapshot Provenance
2. Graph Topology and Key Objects
3. Relationship Structure
4. Validation Findings and Actions

Ground your response strictly in the provided data. Do not use external knowledge or hallucinate. Maintain privacy; do not make external lookups."""

    if ai_provider == "ollama":
        ollama_host = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
        ollama_model = os.environ.get("OLLAMA_MODEL", "llama3.2")
        payload = {
            "model": ollama_model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "stream": False,
        }
        try:
            with httpx.Client(timeout=30.0) as client:
                resp = client.post(f"{ollama_host.rstrip('/')}/api/chat", json=payload)
                resp.raise_for_status()
                data = resp.json()
                text = data["message"]["content"]
                return {
                    "text": text,
                    "model": ollama_model,
                    "provider": "ollama",
                    "timestamp": timestamp,
                    "source_identifiers": source_ids,
                    "disclaimer": "This documentation was generated by AI and requires human review.",
                }
        except Exception as exc:
            raise AIProviderError(f"Ollama documentation generation failed: {exc}")

    elif ai_provider == "gemini":
        gemini_key = os.environ.get("GEMINI_API_KEY", "")
        if not gemini_key:
            raise AIProviderError("Gemini provider requires GEMINI_API_KEY to be set.")
        gemini_model = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash")
        gemini_url = f"https://generativelanguage.googleapis.com/v1beta/models/{gemini_model}:generateContent?key={gemini_key}"
        payload = {
            "contents": [
                {"parts": [{"text": f"{system_prompt}\n\n{user_prompt}"}]}
            ]
        }
        try:
            with httpx.Client(timeout=30.0) as client:
                resp = client.post(gemini_url, json=payload)
                resp.raise_for_status()
                data = resp.json()
                candidates = data.get("candidates", [])
                if not candidates:
                    raise ValueError("No candidates returned by Gemini.")
                text = candidates[0]["content"]["parts"][0]["text"]
                return {
                    "text": text,
                    "model": gemini_model,
                    "provider": "gemini",
                    "timestamp": timestamp,
                    "source_identifiers": source_ids,
                    "disclaimer": "This documentation was generated by AI and requires human review.",
                }
        except Exception as exc:
            raise AIProviderError(f"Gemini documentation generation failed: {exc}")

    else:
        # Default OpenAI compatible endpoint
        ep = os.environ.get("SAP_IM_AI_ENDPOINT") or os.environ.get("OPENAI_BASE_URL") or os.environ.get("OPENAI_API_BASE") or "http://localhost:11434/v1"
        mdl = model or os.environ.get("OPENAI_MODEL", "gpt-4o-mini")
        key = os.environ.get("SAP_IM_AI_API_KEY") or os.environ.get("OPENAI_API_KEY", "")

        payload = {
            "model": mdl,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": 0.2,
        }
        headers = {}
        if key:
            headers["Authorization"] = f"Bearer {key}"

        try:
            url = ep.rstrip("/") + "/chat/completions"
            with httpx.Client(timeout=30.0) as client:
                resp = client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                data = resp.json()
                text = data["choices"][0]["message"]["content"]
                return {
                    "text": text,
                    "model": mdl,
                    "provider": "Local OpenAI-Compatible" if "localhost" in ep or "127.0.0.1" in ep else "openai",
                    "timestamp": timestamp,
                    "source_identifiers": source_ids,
                    "disclaimer": "This documentation was generated by AI and requires human review.",
                }
        except Exception as exc:
            raise AIProviderError(f"Failed to communicate with AI endpoint: {exc}")

